# Generated by Django 5.2 on 2025-04-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatresponse',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='chatresponse',
            name='role',
            field=models.CharField(max_length=1),
        ),
    ]
