# Generated by Django 5.0.14 on 2025-04-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_rename_is_vegetarian_chatresponse_is_vegetarian_or_vegan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
