# Generated by Django 5.0.14 on 2025-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_blacklistedkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedkeyword',
            name='keyword',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
