# Generated by Django 5.2 on 2025-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_timestamp_chatresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatresponse',
            name='is_vegetarian',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
