# Generated by Django 5.2 on 2025-04-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chatresponse_is_vegetarian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatresponse',
            old_name='is_vegetarian',
            new_name='is_vegetarian_or_vegan',
        ),
    ]
